sys.path:
    /Users/jaredquincy/Documents/experimental/foundry_flow
    /Users/jaredquincy/Documents/experimental/foundry_flow/src
    /Users/jaredquincy/Documents/experimental/foundry_flow
    /Library/Frameworks/Python.framework/Versions/3.11/lib/python311.zip
    /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11
    /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload
    /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
Source matching against trees <TreeMatcher source ['/Users/jaredquincy/Documents/experimental/foundry_flow/flow']>
Coverage code matching: <TreeMatcher coverage ['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage']>
Third-party lib matching: <TreeMatcher third ['/Library/Frameworks/Python.framework/Versions/3.11/bin', '/Library/Frameworks/Python.framework/Versions/3.11/lib/python', '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages', '/Users/jaredquincy/Library/Python/3.11/bin', '/Users/jaredquincy/Library/Python/3.11/lib/python3.11/site-packages']>
Source in third-party matching: <TreeMatcher source_in_third []>
-- config ----------------------------------------------------
                         branch: False
                   command_line: None
                    concurrency: -none-
                    config_file: None
         config_files_attempted: /Users/jaredquincy/Documents/experimental/foundry_flow/.coveragerc
                                 /Users/jaredquincy/Documents/experimental/foundry_flow/setup.cfg
                                 /Users/jaredquincy/Documents/experimental/foundry_flow/tox.ini
                                 /Users/jaredquincy/Documents/experimental/foundry_flow/pyproject.toml
              config_files_read: -none-
                        context: None
                    cover_pylib: False
                      data_file: .coverage
                          debug: trace
                                 call
                                 config
                     debug_file: None
               disable_warnings: -none-
                dynamic_context: None
                   exclude_also: -none-
                   exclude_list: #\s*(pragma|PRAGMA)[:\s]?\s*(no|NO)\s*(cover|COVER)
                      extra_css: None
                     fail_under: 0.0
                         format: None
                       html_dir: htmlcov
              html_skip_covered: None
                html_skip_empty: None
                     html_title: Coverage report
                  ignore_errors: False
     include_namespace_packages: False
                    json_output: coverage.json
              json_pretty_print: False
             json_show_contexts: False
            lcov_line_checksums: False
                    lcov_output: coverage.lcov
                       parallel: False
            partial_always_list: while (True|1|False|0):
                                 if (True|1|False|0):
                   partial_list: #\s*(pragma|PRAGMA)[:\s]?\s*(no|NO)\s*(branch|BRANCH)
                          paths: {}
                 plugin_options: {}
                        plugins: -none-
                      precision: 0
                 relative_files: False
                report_contexts: None
                 report_include: None
                    report_omit: None
                    run_include: -none-
                       run_omit: -none-
                  show_contexts: False
                   show_missing: False
                        sigterm: False
                   skip_covered: False
                     skip_empty: False
                           sort: None
                         source: flow
                    source_pkgs: -none-
                          timid: False
                     xml_output: coverage.xml
              xml_package_depth: 99
-- end -------------------------------------------------------
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/_bootstrap.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/_bootstrap_external.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zipimport.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/codecs.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/encodings/aliases.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/encodings/__init__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/encodings/utf_8.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/abc.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/io.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/__main__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/stat.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_collections_abc.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/genericpath.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/posixpath.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/posixpath.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/os.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_sitebuiltins.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_distutils_hack/__init__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/_bootstrap.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/_bootstrap_external.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/warnings.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/machinery.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/_abc.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/keyword.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/operator.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/reprlib.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/types.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/util.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/runpy.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/__future__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/version.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/enum.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_constants.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_casefix.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_compiler.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copyreg.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/platform.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/signal.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_weakrefset.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/abc.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_typing.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/typing.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/env.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_hashlib.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_blake2.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/hashlib.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ntpath.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/exceptions.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/math.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_datetime.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/datetime.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ast.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_opcode.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/opcode.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dis.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/token.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tokenize.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/linecache.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/fnmatch.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/__init__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ipaddress.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/parse.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/types.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/misc.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/files.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/weakref.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/plugin.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/results.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/report_core.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/annotate.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/string.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_types.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_re.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_parser.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/__init__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/tomlconfig.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/config.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/disposition.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/pytracer.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/textwrap.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/traceback.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pprint.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/debug.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/sysmon.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/tracer.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/core.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/glob.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_bisect.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/bisect.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_random.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_sha512.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/random.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_socket.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/select.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/selectors.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/array.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_sqlite3.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/sqlite3/dbapi2.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/sqlite3/__init__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/zlib.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_json.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/scanner.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/numbits.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/sqlitedb.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/sqldata.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/data.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/collector.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/context.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/templite.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/html.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/sysconfig.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/bytecode.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/phystokens.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/parser.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/regions.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/python.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/inorout.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/jsonreport.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_struct.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/struct.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/binascii.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/base64.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/lcovreport.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_compat_pickle.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_pickle.cpython-311-darwin.so': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pickle.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/__main__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/__init__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/multiproc.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/plugin_support.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/report.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/xml/__init__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/xml/dom/domreg.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/xml/dom/__init__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/xml/dom/minicompat.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/xml/dom/NodeFilter.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/xml/dom/xmlbuilder.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/xml/dom/minidom.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/xmlreport.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/control.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/__init__.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/gettext.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/locale.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/optparse.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shlex.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/execfile.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/cmdline.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_sysconfigdata__darwin_darwin.py': falls outside the --source spec
Didn't trace already imported file '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_osx_support.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/execfile.py': falls outside the --source spec
Not tracing '<frozen importlib.util>': original file name is not real
Not tracing '<frozen importlib._bootstrap>': original file name is not real
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_distutils_hack/__init__.py': falls outside the --source spec
Not tracing '<frozen importlib._bootstrap_external>': original file name is not real
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/__init__.py': falls outside the --source spec
Not tracing '<frozen zipimport>': original file name is not real
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/result.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/util.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py': falls outside the --source spec
Not tracing '<string>': original file name is not real
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/difflib.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/heapq.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_compiler.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/enum.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py': falls outside the --source spec
Not tracing '<frozen abc>': original file name is not real
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/suite.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/main.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/argparse.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/runner.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/signals.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/weakref.py': falls outside the --source spec
Not tracing '<frozen posixpath>': original file name is not real
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/files.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/python.py': falls outside the --source spec
Not tracing '<frozen genericpath>': original file name is not real
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/phystokens.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tokenize.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/__main__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/gettext.py': falls outside the --source spec
Not tracing '<frozen _collections_abc>': original file name is not real
Not tracing '<frozen os>': original file name is not real
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/locale.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/encodings/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/bz2.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_compression.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lzma.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/tests/__init__.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/tests/test_clients/__init__.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/tests/test_clients/test_fcp_client.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/mock.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_weakrefset.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/types.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/constants.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/coroutines.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextvars.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/format_helpers.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_futures.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/reprlib.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/exceptions.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_tasks.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/futures.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/protocols.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/transports.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/log.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/staggered.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/locks.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/mixins.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/typing.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/trsock.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/queues.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/subprocess.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/taskgroups.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/timeouts.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/threads.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/unix_events.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_subprocess.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pkgutil.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/exceptions.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/errors.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/parser.py': falls outside the --source spec
Not tracing '<frozen io>': original file name is not real
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/feedparser.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/_policybase.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/header.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/quoprimime.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/base64mime.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/charset.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/encoders.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/quopri.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/utils.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/_parseaddr.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/calendar.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/message.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/_encoded_words.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/email/iterators.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/parse.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/_base_connection.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/connection.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/timeout.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/request.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/util.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/response.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/retry.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/ssl_.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/hmac.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/url.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/ssltransport.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/wait.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/_collections.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/_version.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/queue.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/_request_methods.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/filepost.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/fields.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/mimetypes.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/response.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/http2/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/csv.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zipfile.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/_adapters.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/_text.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/_functools.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/_meta.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/_collections.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/_itertools.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/abc.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/resources/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/resources/_common.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tempfile.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/resources/abc.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/resources/_adapters.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/resources/_legacy.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/textwrap.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/http2/probe.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/ssl_match_hostname.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/proxy.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/poolmanager.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/warnings.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/exceptions.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/compat.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/charset_normalizer/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/charset_normalizer/api.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/charset_normalizer/cd.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/charset_normalizer/constant.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/charset_normalizer/utils.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/charset_normalizer/models.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/charset_normalizer/legacy.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/charset_normalizer/version.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/cookiejar.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/error.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/response.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/cookies.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/packages.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/idna/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/idna/core.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/idna/idnadata.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/idna/intranges.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/idna/package_data.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/utils.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/certs.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/certifi/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/certifi/core.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/__version__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/_internal_utils.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/cookies.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/structures.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/readers.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/resources/readers.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/resources/_itertools.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/api.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/sessions.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/adapters.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/auth.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/encodings/idna.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/stringprep.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/hooks.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/status_codes.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/contrib/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/contrib/socks.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/__init__.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/clients/__init__.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/clients/fcp_client.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/clients/authenticator.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/utils/__init__.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/utils/exceptions/__init__.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/utils/exceptions/authentication_exceptions.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/utils/exceptions/network_exceptions.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/utils/exceptions/api_exceptions.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/utils/exceptions/storage_exceptions.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/models/__init__.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/models/instance.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_migration.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/version.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/errors.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/typing_extensions.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/main.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic_core/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic_core/core_schema.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/decimal.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/numbers.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_config.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/aliases.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_internal_dataclass.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/config.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/warnings.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_decorators.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_repr.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_typing_extra.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zoneinfo/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zoneinfo/_tzpath.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/sysconfig.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zoneinfo/_common.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_docs_extraction.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_import_utils.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_forward_ref.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_generics.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_utils.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_mock_val_ser.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/plugin/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/plugin/_schema_validator.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/uuid.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/annotated_handlers.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/functional_validators.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_core_metadata.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/json_schema.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_discriminated_union.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_known_annotated_metadata.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_signature.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_validate_call.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/fields.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/annotated_types/__init__.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_validators.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/types.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_std_types_schema.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/_internal/_serializers.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/plugin/_loader.py': falls outside the --source spec
Not tracing '<frozen codecs>': original file name is not real
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copyreg.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/models/bid.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/models/instance_type.py': falls outside the --source spec
Not tracing '/Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/models/project.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py': falls outside the --source spec
Authentication failed: Invalid credentials
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/traceback.py': falls outside the --source spec
.HTTP error occurred: Not Found
Failed to cancel bid bid1: API request failed [404]: Not Found
...HTTP error occurred: Internal Server Error
......HTTP error occurred: Internal Server Error
..HTTP error occurred: Bad Request
..HTTP error occurred: Internal Server Error
.Authentication failed with status 401.
.Request exception occurred: Connection error
.
----------------------------------------------------------------------
Ran 17 tests in 0.030s

OK
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/control.py': falls outside the --source spec
Not tracing '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/collector.py': falls outside the --source spec
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/coverage/control.py:892: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
sys.path: ['/Users/jaredquincy/Documents/experimental/foundry_flow/src', '/Users/jaredquincy/Documents/experimental/foundry_flow', '/Users/jaredquincy/Documents/experimental/foundry_flow/src', '/Users/jaredquincy/Documents/experimental/foundry_flow', '/Library/Frameworks/Python.framework/Versions/3.11/lib/python311.zip', '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11', '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages']
flow.clients.fcp_client module is being imported from: /Users/jaredquincy/Documents/experimental/foundry_flow/src/flow/clients/fcp_client.py
Raw API Response: {'id': 'bid1'}
